apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop-app
  namespace: online-shop
  labels:
    app: online-shop-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: online-shop-app
  template:
    metadata:
      labels:
        app: online-shop-app
    spec:
      containers:
      - name: online-shop-app
        image: trainwithshubham/online_shop_app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
