apiVersion: v1
kind: Service
metadata:
  name: online-shop-nodeport
  namespace: online-shop
  labels:
    app: online-shop-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090
    protocol: TCP
  selector:
    app: online-shop-app
