apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx
  labels:
    app.kubernetes.io/component: nginx-pod
    app.kubernetes.io/managed-by: kubernetes-mcp-server
    app.kubernetes.io/name: nginx-pod
    app.kubernetes.io/part-of: kubernetes-mcp-server-run-sandbox
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80
